appId: com.pozitron.hepsiburada
---
# Listeden ilk ürüne koordinatla tıklandı. Ürün kartlarının ID'si yok, koordinat kullanıldı.
- tapOn:
    point: 3%,17%

# Ürün detayında filtre kriterlerine uygunluğu kontrol edildi.
# Regex kullanıldı çünkü büyük/küçük harf farklılıkları olabiliyor.

# Marka kontrolü. Adidas mı?
- assertVisible:
    text: ".*[Aa]didas.*"

# Fiyat 3000-5000 TL aralığında mı kontrol edildi.
- assertVisible:
    text: ".*[3-5]\\.[0-9]{3}.*TL"

# Cinsiyet Erkek mi?
- assertVisible:
    text: ".*[Ee]rkek.*"

# Renk Beyaz mı?
- assertVisible:
    text: ".*[Bb]eyaz.*"

# Numara 42 mi? Tam text kontrolü yapıldı.
- assertVisible:
    text: "Ayakkabı Numarası: 42"

# Sepete ekle butonuna tıklandı.
- tapOn: Sepete ekle

# Sepete eklendi mesajı görünüyor mu kontrol edildi.
- assertVisible: Adidas Strutter Erkek Günlük Spor AyakkabıSepete eklendi

# Sepete git butonuna tıkladık, sepet sayfasına geçildi.
- tapOn: Sepete git
