# ==============================================================================
# TEST: Ürün Seçimi ve Sepete Ekleme
# ==============================================================================
# Adım 7 (devam): Ürün detayında filtre kriterlerinin kontrolü
# Adım 8: Listeleme ekranında yer alan ürünlerden herhangi biri seçilir
# Adım 9: Ürün detay sayfasında "Sepete Ekle" butonuna tıklanır
#
# Beklenen Sonuçlar:
# - Ürün detay sayfası açılır
# - Ürün bilgileri filtre kriterlerine uygun
# - "Sepete eklendi" mesajı görünür
# ==============================================================================

appId: com.pozitron.hepsiburada
---

# ADIM 8: Ürün Seçimi

- tapOn:
    point: 3%,17%

# ADIM 7 (devam): Ürün Detayında Filtre Kontrolü
- assertVisible:
    text: ".*[Aa]didas.*"

- assertVisible:
    text: ".*[3-5]\\.[0-9]{3}.*TL"

- assertVisible:
    text: ".*[Ee]rkek.*"
   
- assertVisible:
    text: ".*[Bb]eyaz.*" 

- assertVisible:
    text: "Ayakkabı Numarası: 42"

# ADIM 9 Sepete ekleme
- tapOn: Sepete ekle

- assertVisible: Adidas Strutter Erkek Günlük Spor AyakkabıSepete eklendi

- tapOn: Sepete git
